apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: has-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/redhat-appstudio/application-service-catalog:sha-4f97678  
  displayName: HAS Operator Catalog
  publisher: Red Hat