resources:
- https://github.com/johnmcollier/application-service/config/kcp?ref=4d6454b214f6021a61a0c968e48f9242b06e5cb2


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/jcollier/application-service
  newTag: kcp

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
