apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - https://github.com/redhat-appstudio/application-service/config/default?ref=a32c938ee1fcafaed4c64abd3ed4864121fd363c

components:
  - ../common/manager-resources
  - ../common/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: a32c938ee1fcafaed4c64abd3ed4864121fd363c

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace



namespace: application-service