apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argocd-roles
  - ../../base/external-secrets
  - https://github.com/redhat-appstudio/application-service/config/default?ref=05ee33115e4cd7ebfad61d96ffe5ef36c8159dab
  - https://github.com/redhat-appstudio/application-service/config/prometheus/?ref=05ee33115e4cd7ebfad61d96ffe5ef36c8159dab

components:
  - ../../common/manager-resources
  - ../../common/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: 05ee33115e4cd7ebfad61d96ffe5ef36c8159dab

configMapGenerator:
- literals:
  - GITHUB_ORG="redhat-appstudio-appdata"
  name: github-config
  behavior: replace

patches:
  - path: has-github-token-patch.yaml
    target:
      name: has-github-token
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
  - path: ./replicas_patch.yaml
namespace: application-service