apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appstudio-shared
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/johnmcollier/infra-deployments.git
        targetRevision: kcp
